windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABmMAAAPyAAAAAAAAAAAAAAZjAAAD8gAAAAAAAAAABocAAAAAAAAA
    AAAABmMAAAPy
  tabs:
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:41'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: status.archlinux.org
      url: https://status.archlinux.org/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:40'
      pinned: true
      scroll-pos:
        x: 0
        y: 0
      title: Inbox | Fastmail
      url: https://app.fastmail.com/mail/Inbox/?u=d8c14067
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'SqrtMinusOne/elfeed-summary: Feed summary interface for elfeed'
      url: https://github.com/SqrtMinusOne/elfeed-summary
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: xenodium
      url: https://github.com/xenodium
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'emacsmirror/highlight-parentheses: Highlight surrounding parentheses'
      url: https://github.com/emacsmirror/highlight-parentheses
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: emacs transient - Google Search
      url: https://www.google.com/search?hl=en&q=emacs%20transient
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Transient for Beginners : r/emacs'
      url: https://www.reddit.com/r/emacs/comments/1gvf3nn/transient_for_beginners/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Transient Menus in Emacs pt. 1 | JD Codes
      url: https://jd.codes/posts/transient-emacs/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-08-27T20:14:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Transient User and Developer Manual
      url: https://www.gnu.org/software/emacs/manual/html_mono/transient.html
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2025-08-27T20:14:48'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: qutebrowser save session location - Google Search
      url: https://www.google.com/search?hl=en&q=qutebrowser%20save%20session%20location
      zoom: 1.0
